### ISSUE TITLE
是否能支持非AMD and CMD形式的插件引入？

### ISSUE THREAD

**Issue by Maple13** [liriliri/eris#1]
我们有的移动端项目没有使用requirejs后者ES6，也没有使用gulp、gunt、webpack，不知是否提供但js文件引用？

**Comment by surunzi** [comment]
打包工具：https://github.com/liriliri/eustia

这个项目本身设计就是脱离webpack使用的，自带打包工具按需引入。使用它自动从Github下载最新代码打包出符合UMD或其它规范的库。可以纯命令行使用，也可以编写配置文件。可以通过扫文件识别引入模块，或直接指定需要的模块。相关文档可查看：http://liriliri.github.io/eustia/docs.html

配置文件范例：
https://github.com/liriliri/eustia/blob/master/.eustia
https://github.com/liriliri/eruda/blob/master/.eustia
https://github.com/liriliri/eris/blob/master/.eustia

以及对应打包出来的js库：
https://github.com/liriliri/eustia/blob/master/lib/util.js
https://github.com/liriliri/eruda/blob/master/src/lib/util.js
https://github.com/liriliri/eris/blob/master/lib/util.js

**Comment by Maple13** [comment]
OK.多谢提点
